### ISSUE TITLE
running example jupyter notebook

### ISSUE THREAD

**Issue by elenzing** [igorauad/link_budget#2]
### Using the example:

pip install link-budget

link-budget \
  --eirp 52 \
  --freq 12.45e9 \
  --if-bw 24e6 \
  --rx-dish-size 0.46 \
  --lnb-noise-fig 0.6 \
  --lnb-gain 40 \
  --coax-length 110 \
  --rx-noise-fig 10 \
  --sat-long -101 \
  --rx-long -82.43 \
  --rx-lat 29.71

If I run this example in jupyter I get the following error:

 File "C:\Users\HPZ620~1\AppData\Local\Temp/ipykernel_19324/319644971.py", line 2
    --eirp 52 \
           ^
SyntaxError: invalid syntax

What am I missing ?

Thanks!

**Comment by igorauad** [comment]
Hi @elenzing ,

It looks like you are trying to run the `link-budget` application within the python interpreter environment, which would be wrong. The `link-budget` application is supposed to run from the regular terminal, such as bash. In this case, you would only need to take care of the link breaks, running like so:

```bash
link-budget \
--eirp 52 \
--freq 12.45e9 \
--if-bw 24e6 \
--rx-dish-size 0.46 \
--lnb-noise-fig 0.6 \
--lnb-gain 40 \
--coax-length 110 \
--rx-noise-fig 10 \
--sat-long -101 \
--rx-long -82.43 \
--rx-lat 29.71
```

However, if you really want to run the calculation from the Python interpreter or embed it on a Python script, you can do so. You can use the following snippet:

```python
from linkbudget import cli

args = [
    '--eirp', 52, '--freq', 12.45e9, '--if-bw', 24e6, '--rx-dish-size', 0.46,
    '--lnb-noise-fig', 0.6, '--lnb-gain', 40, '--coax-length', 110,
    '--rx-noise-fig', 10, '--sat-long', -101, '--rx-long', -82.43, '--rx-lat',
    29.71
]
cli.configure_logging()
parser = cli.get_parser()
args = parser.parse_args(list(map(str, args)))
cli.validate(parser, args)
cli.analyze(args, verbose=True)
```

**Comment by elenzing** [comment]
Mr. Freire,
 Thank you very much for your reply. This was very useful. I am using it to
teach some students about Satellite Communications.

cheers, erik

**Comment by igorauad** [comment]
Hi @elenzing ,

Glad to hear that! Please don't hesitate to ask if you need more help.

Cheers
